<h1>Pandas Tutorial</h1>

In [70]:
import pandas as pd

In [ ]:
# df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], columns=["A", "B", "C"], index=["x","y","z",'zz'])

In [23]:
# df.columns - headers
# df.index.tolist() - index
# df.info() - information about dataframe
# df.describe() - meaningful info about dataframe
# df.nunique() or df.unique
# df[].unique
# df.shape

A    4
B    4
C    4
dtype: int64

In [71]:
tour_data = pd.read_csv('Taylor_Train.csv', encoding='latin1')

In [26]:
tour_data.head()
# First 5 columns

,City,Country,Venue,Opening act(s),Attendance (tickets sold / available),Revenue,Tour
0,Evansville,United States,Roberts Municipal Stadium,Gloriana\r\nKellie Pickler,"7,463 / 7,463","$360,617",Fearless_Tour
1,Jonesboro,United States,Convocation Center,Gloriana\r\nKellie Pickler,"7,822 / 7,822","$340,328",Fearless_Tour
2,St. Louis,United States,Scottrade Center,Gloriana\r\nKellie Pickler,"13,764 / 13,764","$650,420",Fearless_Tour
3,Alexandria,United States,Bishop Ireton High School,Gloriana\r\nKellie Pickler,,,Fearless_Tour
4,North Charleston,United States,North Charleston Coliseum,Gloriana\r\nKellie Pickler,"8,751 / 8,751","$398,154",Fearless_Tour

In [40]:
# tour_data.sample(5)
# tour_data.head()
# tour_data.tail()

,City,Country,Venue,Opening act(s),Attendance (tickets sold / available),Revenue,Tour
249,Glendale,United States,Jobing.com Arena,Ed Sheeran\r\nJoel Crouse,"26,705 / 26,705","$2,239,370",The_Red_Tour
180,Bossier City,United States,CenturyLink Center,Needtobreathe,"11,510 / 11,510","$728,546",Speak_Now_World_Tour
292,Perth,Australia,Perth Rectangular Stadium,Guy Sebastian\r\nNeon Trees,"21,827 / 21,827","$2,364,080",The_Red_Tour
31,Rapid City,United States,Barnett Arena,Gloriana\r\nKellie Pickler,,,Fearless_Tour
310,Bossier City,United States,CenturyLink Center,Vance Joy,"12,459 / 12,459","$1,458,197",The_1989_World_Tour

In [52]:
# tour_data.loc[#Rows, #Columns]
# tour_data.loc[100:105, ["Country", "Tour"]]
# tour_data.iloc[100:105, [1, 6]]
# tour_data.iloc[Rows, Columns] only using index values

           Country           Tour
100         Canada  Fearless_Tour
101         Canada  Fearless_Tour
102         Canada  Fearless_Tour
103  United States  Fearless_Tour
104  United States  Fearless_Tour

In [60]:
# tour_data.sort_values(["Revenue", "Tour"], ascending=True)

In [69]:
tour_data.loc[tour_data["Revenue"] > "$1000000", ['Tour', 'Venue']]

                        Tour                      Venue
0              Fearless_Tour  Roberts Municipal Stadium
1              Fearless_Tour         Convocation Center
2              Fearless_Tour           Scottrade Center
3              Fearless_Tour  Bishop Ireton High School
4              Fearless_Tour  North Charleston Coliseum
..                       ...                        ...
440  Reputation_Stadium_Tour                ANZ Stadium
441  Reputation_Stadium_Tour                  The Gabba
442  Reputation_Stadium_Tour        Mount Smart Stadium
443  Reputation_Stadium_Tour                 Tokyo Dome
444  Reputation_Stadium_Tour                 Tokyo Dome

[348 rows x 2 columns]

In [ ]:
tour_data[tour_data['Revenue'] > 100000] # when data is numeric and not strings
filtered_data = tour_data[(tour_data['Revenue'] > 1000000) & (tour_data['City_Chicago'] == 1)] # when data is numeric

In [73]:
tour_data[tour_data['Tour'] == 'Reputation_Stadium_Tour']

,City,Country,Venue,Opening act(s),Attendance (tickets sold / available),Revenue,Tour
392,Glendale,United States,University of Phoenix Stadium,Camila Cabello\r\nCharli XCX,"59,157 / 59,157","$7,214,478",Reputation_Stadium_Tour
393,Santa Clara,United States,Levi's Stadium,Camila Cabello\r\nCharli XCX,"107,550 / 107,550","$14,006,963",Reputation_Stadium_Tour
394,Santa Clara,United States,Levi's Stadium,Camila Cabello\r\nCharli XCX,"107,550 / 107,550","$14,006,963",Reputation_Stadium_Tour
395,Pasadena,United States,Rose Bowl,Camila Cabello\r\nCharli XCX,"118,084 / 118,084","$16,251,980",Reputation_Stadium_Tour
396,Pasadena,United States,Rose Bowl,Camila Cabello\r\nCharli XCX,"118,084 / 118,084","$16,251,980",Reputation_Stadium_Tour
397,Seattle,United States,CenturyLink Field,Charli XCX,"56,021 / 56,021","$8,672,219",Reputation_Stadium_Tour
398,Denver,United States,Sports Authority Field at Mile High,Camila Cabello\r\nCharli XCX,"57,140 / 57,140","$7,926,366",Reputation_Stadium_Tour
399,Chicago,United States,Soldier Field,Camila Cabello\r\nCharli XCX,"105,208 / 105,208","$14,576,697",Reputation_Stadium_Tour
400,Chicago,United States,Soldier Field,Camila Cabello\r\nCharli XCX,"105,208 / 105,208","$14,576,697",Reputation_Stadium_Tour
401,Manchester,England,Etihad Stadium,Camila Cabello\r\nCharli XCX,"77,258 / 77,258","$6,169,724",Reputation_Stadium_Tour
402,Manchester,England,Etihad Stadium,Camila Cabello\r\nCharli XCX,"77,258 / 77,258","$6,169,724",Reputation_Stadium_Tour
403,Dublin,Ireland,Croke Park,Camila Cabello\r\nCharli XCX,"133,034 / 133,034","$8,567,769",Reputation_Stadium_Tour
404,Dublin,Ireland,Croke Park,Camila Cabello\r\nCharli XCX,"133,034 / 133,034","$8,567,769",Reputation_Stadium_Tour
405,London,England,Wembley Stadium,Camila Cabello\r\nCharli XCX,"143,427 / 143,427","$12,214,933",Reputation_Stadium_Tour
406,London,England,Wembley Stadium,Camila Cabello\r\nCharli XCX,"143,427 / 143,427","$12,214,933",Reputation_Stadium_Tour
407,Louisville,United States,Cardinal Stadium,Camila Cabello\r\nCharli XCX,"52,138 / 52,138","$4,928,219",Reputation_Stadium_Tour
408,Columbus,United States,Ohio Stadium,Camila Cabello\r\nCharli XCX,"62,897 / 62,897","$6,606,529",Reputation_Stadium_Tour
409,Landover,United States,FedExField,Camila Cabello\r\nCharli XCX,"95,672 / 95,672","$11,396,004",Reputation_Stadium_Tour
410,Landover,United States,FedExField,Camila Cabello\r\nCharli XCX,"95,672 / 95,672","$11,396,004",Reputation_Stadium_Tour
411,Philadelphia,United States,Lincoln Financial Field,Camila Cabello\r\nCharli XCX,"107,378 / 107,378","$11,951,047",Reputation_Stadium_Tour
412,Philadelphia,United States,Lincoln Financial Field,Camila Cabello\r\nCharli XCX,"107,378 / 107,378","$11,951,047",Reputation_Stadium_Tour
413,Cleveland,United States,FirstEnergy Stadium,Camila Cabello\r\nCharli XCX,"51,323 / 51,323","$5,148,757",Reputation_Stadium_Tour
414,East Rutherford,United States,MetLife Stadium,Camila Cabello\r\nCharli XCX,"165,654 / 165,654","$22,031,386",Reputation_Stadium_Tour
415,East Rutherford,United States,MetLife Stadium,Camila Cabello\r\nCharli XCX,"165,654 / 165,654","$22,031,386",Reputation_Stadium_Tour
416,East Rutherford,United States,MetLife Stadium,Camila Cabello\r\nCharli XCX,"165,654 / 165,654","$22,031,386",Reputation_Stadium_Tour
417,Foxborough,United States,Gillette Stadium,Camila Cabello\r\nCharli XCX,"174,764 / 174,764","$21,779,846",Reputation_Stadium_Tour
418,Foxborough,United States,Gillette Stadium,Camila Cabello\r\nCharli XCX,"174,764 / 174,764","$21,779,846",Reputation_Stadium_Tour
419,Foxborough,United States,Gillette Stadium,Camila Cabello\r\nCharli XCX,"174,764 / 174,764","$21,779,846",Reputation_Stadium_Tour
420,Toronto,Canada,Rogers Centre,Camila Cabello\r\nCharli XCX,"100,310 / 100,310","$11,177,000",Reputation_Stadium_Tour
421,Toronto,Canada,Rogers Centre,Camila Cabello\r\nCharli XCX,"100,310 / 100,310","$11,177,000",Reputation_Stadium_Tour
422,Pittsburgh,United States,Heinz Field,Camila Cabello\r\nCharli XCX,"56,445 / 56,445","$6,230,876",Reputation_Stadium_Tour
423,Atlanta,United States,Mercedes-Benz Stadium,Camila Cabello\r\nCharli XCX,"116,746 / 116,746","$18,089,415",Reputation_Stadium_Tour
424,Atlanta,United States,Mercedes-Benz Stadium,Camila Cabello\r\nCharli XCX,"116,746 / 116,746","$18,089,415",Reputation_Stadium_Tour
425,Tampa,United States,Raymond James Stadium,Camila Cabello\r\nCharli XCX,"55,909 / 55,909","$7,244,264",Reputation_Stadium_Tour
426,Miami Gardens,United States,Hard Rock Stadium,Camila Cabello\r\nCharli XCX,"47,818 / 47,818","$7,072,164",Reputation_Stadium_Tour
427,Nashville,United States,Nissan Stadium,Camila Cabello\r\nCharli XCX,"56,112 / 56,112","$9,007,179",Reputation_Stadium_Tour
428,Detroit,United States,Ford Field,Camila Cabello\r\nCharli XCX,"49,464 / 49,464","$6,597,852",Reputation_Stadium_Tour
429,Minneapolis,United States,U.S. Bank Stadium,Camila Cabello\r\nCharli XCX,"98,774 / 98,774","$10,242,024",Reputation_Stadium_Tour
430,Minneapolis,United States,U.S. Bank Stadium,Camila Cabello\r\nCharli XCX,"98,774 / 98,774","$10,242,024",Reputation_Stadium_Tour
431,Kansas City,United States,Arrowhead Stadium,Camila Cabello\r\nCharli XCX,"58,611 / 58,611","$6,730,138",Reputation_Stadium_Tour
432,Indianapolis,United States,Lucas Oil Stadium,Camila Cabello\r\nCharli XCX,"55,729 / 55,729","$6,531,245",Reputation_Stadium_Tour
433,St. Louis,United States,The Dome at America's Center,Camila Cabello\r\nCharli XCX,"47,831 / 47,831","$4,884,054",Reputation_Stadium_Tour
434,New Orleans,United States,Mercedes-Benz Superdome,Camila Cabello\r\nCharli XCX,"53,172 / 53,172","$6,491,546",Reputation_Stadium_Tour
435,Houston,United States,NRG Stadium,Camila Cabello\r\nCharli XCX,"53,800 / 53,800","$9,350,275",Reputation_Stadium_Tour
436,Arlington,United States,AT&T Stadium,Camila Cabello\r\nCharli XCX,"105,002 / 105,002","$15,006,157",Reputation_Stadium_Tour
437,Arlington,United States,AT&T Stadium,Camila Cabello\r\nCharli XCX,"105,002 / 105,002","$15,006,157",Reputation_Stadium_Tour
438,Perth,Australia,Optus Stadium,Charli XCX\r\nBroods,"50,891 / 50,891","$4,153,658",Reputation_Stadium_Tour
439,Melbourne,Australia,Marvel Stadium,Charli XCX\r\nBroods,"63,027 / 63,027","$6,755,570",Reputation_Stadium_Tour
440,Sydney,Australia,ANZ Stadium,Charli XCX\r\nBroods,"72,805 / 72,805","$7,686,564",Reputation_Stadium_Tour
441,Brisbane,Australia,The Gabba,Charli XCX\r\nBroods,"43,907 / 43,907","$4,338,127",Reputation_Stadium_Tour
442,Auckland,New Zealand,Mount Smart Stadium,Charli XCX\r\nBroods,"35,749 / 35,749","$3,617,593",Reputation_Stadium_Tour
443,Tokyo,Japan,Tokyo Dome,Charli XCX,"100,109 / 100,109","$14,859,847",Reputation_Stadium_Tour
444,Tokyo,Japan,Tokyo Dome,Charli XCX,"100,109 / 100,109","$14,859,847",Reputation_Stadium_Tour

In [75]:
tour_data[tour_data['Opening act(s)'].str.contains("Charli XCX", na=False)]

,City,Country,Venue,Opening act(s),Attendance (tickets sold / available),Revenue,Tour
392,Glendale,United States,University of Phoenix Stadium,Camila Cabello\r\nCharli XCX,"59,157 / 59,157","$7,214,478",Reputation_Stadium_Tour
393,Santa Clara,United States,Levi's Stadium,Camila Cabello\r\nCharli XCX,"107,550 / 107,550","$14,006,963",Reputation_Stadium_Tour
394,Santa Clara,United States,Levi's Stadium,Camila Cabello\r\nCharli XCX,"107,550 / 107,550","$14,006,963",Reputation_Stadium_Tour
395,Pasadena,United States,Rose Bowl,Camila Cabello\r\nCharli XCX,"118,084 / 118,084","$16,251,980",Reputation_Stadium_Tour
396,Pasadena,United States,Rose Bowl,Camila Cabello\r\nCharli XCX,"118,084 / 118,084","$16,251,980",Reputation_Stadium_Tour
397,Seattle,United States,CenturyLink Field,Charli XCX,"56,021 / 56,021","$8,672,219",Reputation_Stadium_Tour
398,Denver,United States,Sports Authority Field at Mile High,Camila Cabello\r\nCharli XCX,"57,140 / 57,140","$7,926,366",Reputation_Stadium_Tour
399,Chicago,United States,Soldier Field,Camila Cabello\r\nCharli XCX,"105,208 / 105,208","$14,576,697",Reputation_Stadium_Tour
400,Chicago,United States,Soldier Field,Camila Cabello\r\nCharli XCX,"105,208 / 105,208","$14,576,697",Reputation_Stadium_Tour
401,Manchester,England,Etihad Stadium,Camila Cabello\r\nCharli XCX,"77,258 / 77,258","$6,169,724",Reputation_Stadium_Tour
402,Manchester,England,Etihad Stadium,Camila Cabello\r\nCharli XCX,"77,258 / 77,258","$6,169,724",Reputation_Stadium_Tour
403,Dublin,Ireland,Croke Park,Camila Cabello\r\nCharli XCX,"133,034 / 133,034","$8,567,769",Reputation_Stadium_Tour
404,Dublin,Ireland,Croke Park,Camila Cabello\r\nCharli XCX,"133,034 / 133,034","$8,567,769",Reputation_Stadium_Tour
405,London,England,Wembley Stadium,Camila Cabello\r\nCharli XCX,"143,427 / 143,427","$12,214,933",Reputation_Stadium_Tour
406,London,England,Wembley Stadium,Camila Cabello\r\nCharli XCX,"143,427 / 143,427","$12,214,933",Reputation_Stadium_Tour
407,Louisville,United States,Cardinal Stadium,Camila Cabello\r\nCharli XCX,"52,138 / 52,138","$4,928,219",Reputation_Stadium_Tour
408,Columbus,United States,Ohio Stadium,Camila Cabello\r\nCharli XCX,"62,897 / 62,897","$6,606,529",Reputation_Stadium_Tour
409,Landover,United States,FedExField,Camila Cabello\r\nCharli XCX,"95,672 / 95,672","$11,396,004",Reputation_Stadium_Tour
410,Landover,United States,FedExField,Camila Cabello\r\nCharli XCX,"95,672 / 95,672","$11,396,004",Reputation_Stadium_Tour
411,Philadelphia,United States,Lincoln Financial Field,Camila Cabello\r\nCharli XCX,"107,378 / 107,378","$11,951,047",Reputation_Stadium_Tour
412,Philadelphia,United States,Lincoln Financial Field,Camila Cabello\r\nCharli XCX,"107,378 / 107,378","$11,951,047",Reputation_Stadium_Tour
413,Cleveland,United States,FirstEnergy Stadium,Camila Cabello\r\nCharli XCX,"51,323 / 51,323","$5,148,757",Reputation_Stadium_Tour
414,East Rutherford,United States,MetLife Stadium,Camila Cabello\r\nCharli XCX,"165,654 / 165,654","$22,031,386",Reputation_Stadium_Tour
415,East Rutherford,United States,MetLife Stadium,Camila Cabello\r\nCharli XCX,"165,654 / 165,654","$22,031,386",Reputation_Stadium_Tour
416,East Rutherford,United States,MetLife Stadium,Camila Cabello\r\nCharli XCX,"165,654 / 165,654","$22,031,386",Reputation_Stadium_Tour
417,Foxborough,United States,Gillette Stadium,Camila Cabello\r\nCharli XCX,"174,764 / 174,764","$21,779,846",Reputation_Stadium_Tour
418,Foxborough,United States,Gillette Stadium,Camila Cabello\r\nCharli XCX,"174,764 / 174,764","$21,779,846",Reputation_Stadium_Tour
419,Foxborough,United States,Gillette Stadium,Camila Cabello\r\nCharli XCX,"174,764 / 174,764","$21,779,846",Reputation_Stadium_Tour
420,Toronto,Canada,Rogers Centre,Camila Cabello\r\nCharli XCX,"100,310 / 100,310","$11,177,000",Reputation_Stadium_Tour
421,Toronto,Canada,Rogers Centre,Camila Cabello\r\nCharli XCX,"100,310 / 100,310","$11,177,000",Reputation_Stadium_Tour
422,Pittsburgh,United States,Heinz Field,Camila Cabello\r\nCharli XCX,"56,445 / 56,445","$6,230,876",Reputation_Stadium_Tour
423,Atlanta,United States,Mercedes-Benz Stadium,Camila Cabello\r\nCharli XCX,"116,746 / 116,746","$18,089,415",Reputation_Stadium_Tour
424,Atlanta,United States,Mercedes-Benz Stadium,Camila Cabello\r\nCharli XCX,"116,746 / 116,746","$18,089,415",Reputation_Stadium_Tour
425,Tampa,United States,Raymond James Stadium,Camila Cabello\r\nCharli XCX,"55,909 / 55,909","$7,244,264",Reputation_Stadium_Tour
426,Miami Gardens,United States,Hard Rock Stadium,Camila Cabello\r\nCharli XCX,"47,818 / 47,818","$7,072,164",Reputation_Stadium_Tour
427,Nashville,United States,Nissan Stadium,Camila Cabello\r\nCharli XCX,"56,112 / 56,112","$9,007,179",Reputation_Stadium_Tour
428,Detroit,United States,Ford Field,Camila Cabello\r\nCharli XCX,"49,464 / 49,464","$6,597,852",Reputation_Stadium_Tour
429,Minneapolis,United States,U.S. Bank Stadium,Camila Cabello\r\nCharli XCX,"98,774 / 98,774","$10,242,024",Reputation_Stadium_Tour
430,Minneapolis,United States,U.S. Bank Stadium,Camila Cabello\r\nCharli XCX,"98,774 / 98,774","$10,242,024",Reputation_Stadium_Tour
431,Kansas City,United States,Arrowhead Stadium,Camila Cabello\r\nCharli XCX,"58,611 / 58,611","$6,730,138",Reputation_Stadium_Tour
432,Indianapolis,United States,Lucas Oil Stadium,Camila Cabello\r\nCharli XCX,"55,729 / 55,729","$6,531,245",Reputation_Stadium_Tour
433,St. Louis,United States,The Dome at America's Center,Camila Cabello\r\nCharli XCX,"47,831 / 47,831","$4,884,054",Reputation_Stadium_Tour
434,New Orleans,United States,Mercedes-Benz Superdome,Camila Cabello\r\nCharli XCX,"53,172 / 53,172","$6,491,546",Reputation_Stadium_Tour
435,Houston,United States,NRG Stadium,Camila Cabello\r\nCharli XCX,"53,800 / 53,800","$9,350,275",Reputation_Stadium_Tour
436,Arlington,United States,AT&T Stadium,Camila Cabello\r\nCharli XCX,"105,002 / 105,002","$15,006,157",Reputation_Stadium_Tour
437,Arlington,United States,AT&T Stadium,Camila Cabello\r\nCharli XCX,"105,002 / 105,002","$15,006,157",Reputation_Stadium_Tour
438,Perth,Australia,Optus Stadium,Charli XCX\r\nBroods,"50,891 / 50,891","$4,153,658",Reputation_Stadium_Tour
439,Melbourne,Australia,Marvel Stadium,Charli XCX\r\nBroods,"63,027 / 63,027","$6,755,570",Reputation_Stadium_Tour
440,Sydney,Australia,ANZ Stadium,Charli XCX\r\nBroods,"72,805 / 72,805","$7,686,564",Reputation_Stadium_Tour
441,Brisbane,Australia,The Gabba,Charli XCX\r\nBroods,"43,907 / 43,907","$4,338,127",Reputation_Stadium_Tour
442,Auckland,New Zealand,Mount Smart Stadium,Charli XCX\r\nBroods,"35,749 / 35,749","$3,617,593",Reputation_Stadium_Tour
443,Tokyo,Japan,Tokyo Dome,Charli XCX,"100,109 / 100,109","$14,859,847",Reputation_Stadium_Tour
444,Tokyo,Japan,Tokyo Dome,Charli XCX,"100,109 / 100,109","$14,859,847",Reputation_Stadium_Tour

In [77]:
tour_data[tour_data['Country'].isin(['Germany', 'France', 'England'])]

,City,Country,Venue,Opening act(s),Attendance (tickets sold / available),Revenue,Tour
7,London,England,Shepherd's Bush Empire,,"6,789 / 6,789","$401,328",Fearless_Tour
8,London,England,Shepherd's Bush Empire,,"6,789 / 6,789","$401,328",Fearless_Tour
36,Chelmsford,England,Hylands Park,,,,Fearless_Tour
37,Weston-under-Lizard,England,Weston Park,,,,Fearless_Tour
59,London,England,Wembley Arena,Justin Bieber,,,Fearless_Tour
60,Manchester,England,Manchester Evening News Arena,Justin Bieber,,,Fearless_Tour
121,Oberhausen,Germany,König Pilsener Arena,Martin & James,"6,082 / 6,082","$370,028",Speak_Now_World_Tour
123,Paris,France,Zénith de Paris,,"3,598 / 8,500","$201,781",Speak_Now_World_Tour
125,Birmingham,England,LG Arena,Martin & James,"9,339 / 9,339","$508,854",Speak_Now_World_Tour
128,Manchester,England,Manchester Evening News Arena,Martin & James,"10,488 / 11,622","$580,558",Speak_Now_World_Tour
129,London,England,The O2 Arena,Martin & James,"15,265 / 15,681","$891,152",Speak_Now_World_Tour
294,London,England,The O2 Arena,The Vamps,"74,740 / 74,740","$5,829,240",The_Red_Tour
295,London,England,The O2 Arena,The Vamps,"74,740 / 74,740","$5,829,240",The_Red_Tour
296,London,England,The O2 Arena,The Vamps,"74,740 / 74,740","$5,829,240",The_Red_Tour
297,Berlin,Germany,O2 World,Andreas Bourani,"10,350 / 10,350","$755,006",The_Red_Tour
298,London,England,The O2 Arena,The Vamps,NaN,NaN,The_Red_Tour
299,London,England,The O2 Arena,The Vamps,NaN,NaN,The_Red_Tour
320,Cologne,Germany,Lanxess Arena,James Bay,"29,020 / 29,020","$2,054,690",The_1989_World_Tour
321,Cologne,Germany,Lanxess Arena,James Bay,"29,020 / 29,020","$2,054,690",The_1989_World_Tour
324,Manchester,England,Manchester Arena,Vance Joy,"14,773 / 14,773","$1,478,760",The_1989_World_Tour
325,London,England,Hyde Park,,,,The_1989_World_Tour
401,Manchester,England,Etihad Stadium,Camila Cabello\r\nCharli XCX,"77,258 / 77,258","$6,169,724",Reputation_Stadium_Tour
402,Manchester,England,Etihad Stadium,Camila Cabello\r\nCharli XCX,"77,258 / 77,258","$6,169,724",Reputation_Stadium_Tour
405,London,England,Wembley Stadium,Camila Cabello\r\nCharli XCX,"143,427 / 143,427","$12,214,933",Reputation_Stadium_Tour
406,London,England,Wembley Stadium,Camila Cabello\r\nCharli XCX,"143,427 / 143,427","$12,214,933",Reputation_Stadium_Tour

In [80]:
tour_data.query('Tour == "The_1989_World_Tour" and City == "Los Angeles"')

,City,Country,Venue,Opening act(s),Attendance (tickets sold / available),Revenue,Tour
346,Los Angeles,United States,Staples Center,Vance Joy\r\nHaim,"70,563 / 70,563","$8,961,681",The_1989_World_Tour
347,Los Angeles,United States,Staples Center,Vance Joy\r\nHaim,"70,563 / 70,563","$8,961,681",The_1989_World_Tour
348,Los Angeles,United States,Staples Center,Vance Joy\r\nHaim,"70,563 / 70,563","$8,961,681",The_1989_World_Tour
349,Los Angeles,United States,Staples Center,Vance Joy\r\nHaim,"70,563 / 70,563","$8,961,681",The_1989_World_Tour
350,Los Angeles,United States,Staples Center,Vance Joy\r\nHaim,"70,563 / 70,563","$8,961,681",The_1989_World_Tour

In [81]:
tour_data['Taylors Version?'] = True

In [85]:
import numpy as np

tour_data['Taylors Version?'] = np.where(tour_data['Tour']=='Reputation_Stadium_Tour', False, True)

In [87]:
tour_data.tail()

,City,Country,Venue,Opening act(s),Attendance (tickets sold / available),Revenue,Tour,Taylors Version?
440,Sydney,Australia,ANZ Stadium,Charli XCX\r\nBroods,"72,805 / 72,805","$7,686,564",Reputation_Stadium_Tour,False
441,Brisbane,Australia,The Gabba,Charli XCX\r\nBroods,"43,907 / 43,907","$4,338,127",Reputation_Stadium_Tour,False
442,Auckland,New Zealand,Mount Smart Stadium,Charli XCX\r\nBroods,"35,749 / 35,749","$3,617,593",Reputation_Stadium_Tour,False
443,Tokyo,Japan,Tokyo Dome,Charli XCX,"100,109 / 100,109","$14,859,847",Reputation_Stadium_Tour,False
444,Tokyo,Japan,Tokyo Dome,Charli XCX,"100,109 / 100,109","$14,859,847",Reputation_Stadium_Tour,False

In [97]:
# tour_data.dropna(how='any', axis=0)

,City,Country,Venue,Tour,Taylors Version?
0,Evansville,United States,Roberts Municipal Stadium,Fearless_Tour,True
1,Jonesboro,United States,Convocation Center,Fearless_Tour,True
2,St. Louis,United States,Scottrade Center,Fearless_Tour,True
3,Alexandria,United States,Bishop Ireton High School,Fearless_Tour,True
4,North Charleston,United States,North Charleston Coliseum,Fearless_Tour,True
...,...,...,...,...,...
440,Sydney,Australia,ANZ Stadium,Reputation_Stadium_Tour,False
441,Brisbane,Australia,The Gabba,Reputation_Stadium_Tour,False
442,Auckland,New Zealand,Mount Smart Stadium,Reputation_Stadium_Tour,False
443,Tokyo,Japan,Tokyo Dome,Reputation_Stadium_Tour,False
444,Tokyo,Japan,Tokyo Dome,Reputation_Stadium_Tour,False

In [98]:
# tour_data.head()

,City,Country,Venue,Tour,Taylors Version?
0,Evansville,United States,Roberts Municipal Stadium,Fearless_Tour,True
1,Jonesboro,United States,Convocation Center,Fearless_Tour,True
2,St. Louis,United States,Scottrade Center,Fearless_Tour,True
3,Alexandria,United States,Bishop Ireton High School,Fearless_Tour,True
4,North Charleston,United States,North Charleston Coliseum,Fearless_Tour,True